name: Android SDK with Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '31.0.0'
          ndk-version: '23.1.7779620'

      - name: Build with Gradle
        run: ./gradlew build
