name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '31.0.0'
          emulator-version: '30.7.5'
          arch: 'x86'
          api-level: 30
          license: ${{ secrets.ANDROID_SDK_LICENSE }}

      - name: Build Android project
        run: |
          ./gradlew assembleDebug
