name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Deploy
        uses: my-org/my-deploy-action@v1
        with:
          environment: production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
